### ISSUE TITLE
 [Bug]vela-core will crash when rolloutBatches is empty

### ISSUE THREAD

**Issue by wangyikewxgm** [oam-dev/kubevela#1631]
**Describe the bug**
Now, AppRollout's `spec.rolloutPlan.rolloutBatches` is optional but if we create a AppRollout without rolloutBatches 
KubeVela controller will crash

**To Reproduce**
1. apply the appRollout yaml
```yaml
apiVersion: core.oam.dev/v1beta1
kind: AppRollout
metadata:
  name: rolling-example
spec:
  targetAppRevisionName: test-rolling-v1
  componentList:
    - metrics-provider
  rolloutPlan:
    rolloutStrategy: "IncreaseFirst"
    targetSize: 2
```
2. vela core will crash, check the log
```shell
E0510 07:22:50.819047       1 runtime.go:78] Observed a panic: runtime.boundsError{x:-1, y:0, signed:true, code:0x0} (runtime error: index out of range [-1])
goroutine 573 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1c5a220, 0xc00a4f67e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1c5a220, 0xc00a4f67e0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/oam-dev/kubevela/pkg/controller/common/rollout/workloads.verifyBatchesWithScale(0xc007a8c180, 0x1, 0x3, 0x0, 0x0)
        /workspace/pkg/controller/common/rollout/workloads/common.go:88 +0x4ba
github.com/oam-dev/kubevela/pkg/controller/common/rollout/workloads.(*DeploymentScaleController).VerifySpec(0xc00ae9eb60, 0x20a0060, 0xc00757b2c0, 0x0, 0x0, 0x0)
        /workspace/pkg/controller/common/rollout/workloads/deployment_scale_controller.go:91 +0x2f0
github.com/oam-dev/kubevela/pkg/controller/common/rollout.(*Controller).Reconcile(0xc0007c4050, 0x20a0060, 0xc00757b2c0, 0xc0004ff600, 0x12a05f200, 0xc00ae9e9a0)
        /workspace/pkg/controller/common/rollout/rollout_plan_controller.go:115 +0x782
github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationrollout.(*Reconciler).DoReconcile(0xc005f7cfc0, 0x20a0060, 0xc00757b2c0, 0xc0004ff680, 0x0, 0xc00670f4e0, 0x0, 0x1)
        /workspace/pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go:228 +0xc41
github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/application.(*appHandler).handleRollout(0xc00092aa80, 0x20a0060, 0xc00757b2c0, 0xc00a792800, 0xc000568000, 0xc0096ed018, 0x1)
        /workspace/pkg/controller/core.oam.dev/v1alpha2/application/apply.go:748 +0x40e
github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/application.(*Reconciler).Reconcile(0xc009b85ab0, 0xc00a82d6f9, 0x7, 0xc00a82d6e0, 0xc, 0xc00689cde0, 0xc009904750, 0xc0099046c8, 0xc0099046c0)
        /workspace/pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go:178 +0x2355
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0009b8360, 0x1b9e220, 0xc008da1840, 0x0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235 +0x284
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0009b8360, 0x203000)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0009b8360)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc005fb9610)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc005fb9610, 0x2059660, 0xc009f450e0, 0x1, 0xc00045f200)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc005fb9610, 0x3b9aca00, 0x0, 0x1, 0xc00045f200)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc005fb9610, 0x3b9aca00, 0xc00045f200)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:170 +0x411
panic: runtime error: index out of range [-1] [recovered]
        panic: runtime error: index out of range [-1]

```

**Expected behavior**

**Screenshots**

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
even without webhook, we should also prevent the controller crash, please fix it ASAP @wangyikewxgm

**Comment by wangyikewxgm** [comment]
Yes, I found I have disabled the AppRollout webhook. And the application webhook don't verify  `spec.rolloutPlan`, I will fix it.
