### ISSUE TITLE
[BUG]`vela comp run` occurs panic if not set any args

### ISSUE THREAD

**Issue by mosesyou** [oam-dev/kubevela#283]
```
$ vela comp run
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/oam-dev/kubevela/pkg/commands.NewCompRunCommands.func1(0xc0007158c0, 0x40c1920, 0x0, 0x0, 0x0, 0x0)
	/Users/admin/software/mosesyou/kubevela/pkg/commands/comp.go:62 +0x2bb
github.com/spf13/cobra.(*Command).execute(0xc0007158c0, 0x40c1920, 0x0, 0x0, 0xc0007158c0, 0x40c1920)
	/Users/admin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000244000, 0x16353d891d2c1328, 0x4085660, 0xc00010e058)
	/Users/admin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/admin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/admin/software/mosesyou/kubevela/cmd/vela/main.go:47 +0x8c
exit status 2
```

**Comment by wonderflow** [comment]
@mosesyou  thanks for reporting, would you like to send a PR?

**Comment by mosesyou** [comment]
sure

**Comment by wonderflow** [comment]
thanks @mosesyou
