### ISSUE TITLE
panic error when up the application

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/kubevela#3755]
**Describe the bug**

```
$ vela up -f first.yaml
Applying an application in vela K8s object format...
I0426 12:22:10.933654   29792 apply.go:107] "patching object" name="first-vela-app" resource="core.oam.dev/v1beta1, Kind=Application"
panic: interface conversion: error is *errors.withStack, not *errors.StatusError

goroutine 1 [running]:
k8s.io/kubectl/pkg/cmd/util.checkErr({0x39ccbc0, 0xc000931a10}, 0x3659e40)
	/home/runner/go/pkg/mod/k8s.io/kubectl@v0.21.0/pkg/cmd/util/helpers.go:146 +0x8cb
k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
	/home/runner/go/pkg/mod/k8s.io/kubectl@v0.21.0/pkg/cmd/util/helpers.go:115
github.com/oam-dev/kubevela/references/cli.NewUpCommand.func2(0xc000973400, {0xc000367580, 0x0, 0x2})
	/home/runner/work/kubevela/kubevela/references/cli/up.go:285 +0x105
github.com/spf13/cobra.(*Command).execute(0xc000973400, {0xc000367560, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000972280)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/runner/work/kubevela/kubevela/references/cmd/cli/main.go:39 +0xef
```

**KubeVela Version**

CLI Version: v1.4.0-alpha.2
Core Version: 1.3.2
GitRevision: git-2d28fb3
GolangVersion: go1.17.8

**Comment by Somefive** [comment]
Solved in #3759
