### ISSUE TITLE
 make npm-install failed

### ISSUE THREAD

**Issue by xishengcai** [oam-dev/kubevela#377]
**Describe the bug**
make npm-install failed
```
XishengdeMacBook-Pro:kubevela xishengcai$ make npm-install
cd dashboard && npm install && cd ./..

> node-pty@0.10.0-beta9 install /Users/xishengcai/go/src/github.com/oam-dev/kubevela/dashboard/node_modules/node-pty
> node scripts/install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xishengcai/go/src/github.com/oam-dev/kubevela/dashboard/node_modules/node-pty
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> micro-app-engine@4.2.0 postinstall /Users/xishengcai/go/src/github.com/oam-dev/kubevela/dashboard
> umi g tmp

npm WARN @umijs/plugin-layout@0.12.2 requires a peer of @ant-design/pro-layout@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-dva-hmr@0.4.2 requires a peer of redbox-react@1.x but none is installed. You must install peer dependencies yourself.
npm WARN connected-react-router@6.5.2 requires a peer of react-redux@^6.0.0 || ^7.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN dva-core@1.4.0 requires a peer of redux@3.x but none is installed. You must install peer dependencies yourself.
npm WARN dva-immer@0.5.0 requires a peer of dva@^2.5.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN dva-loading@3.0.21 requires a peer of dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-pty@0.10.0-beta9 (node_modules/node-pty):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-pty@0.10.0-beta9 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 2996 packages in 15.957s

158 packages are looking for funding
  run `npm fund` for details

```

**To Reproduce**
make npm-install

**Expected behavior**

**Cluster information**
kubernetes: v1.17.11
MacOS:       Catalina 10.15.6
Node.js:       v12.18.1
![image](https://user-images.githubusercontent.com/21197150/95699414-f28e0500-0c76-11eb-9a1e-cfe9985ec35b.png)

**Comment by wonderflow** [comment]
I noticed your error information contains `No Xcode or CLT version detected`

And I googled for the answer here: https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d

Hope you have a try.

Closing As it seems not an issue by `kubevela`, feel free to open it if there's still some errors.
